# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/scorpy/Documents/syla-tiles

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/scorpy/Documents/syla-tiles

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/scorpy/Documents/syla-tiles/CMakeFiles /Users/scorpy/Documents/syla-tiles/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/scorpy/Documents/syla-tiles/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ser

# Build rule for target.
ser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ser
.PHONY : ser

# fast build rule for target.
ser/fast:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/build
.PHONY : ser/fast

#=============================================================================
# Target rules for targets named syla

# Build rule for target.
syla: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 syla
.PHONY : syla

# fast build rule for target.
syla/fast:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/build
.PHONY : syla/fast

src/client/client.o: src/client/client.cpp.o

.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i

.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s

.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/game/control_keys.o: src/game/control_keys.cpp.o

.PHONY : src/game/control_keys.o

# target to build an object file
src/game/control_keys.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/control_keys.cpp.o
.PHONY : src/game/control_keys.cpp.o

src/game/control_keys.i: src/game/control_keys.cpp.i

.PHONY : src/game/control_keys.i

# target to preprocess a source file
src/game/control_keys.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/control_keys.cpp.i
.PHONY : src/game/control_keys.cpp.i

src/game/control_keys.s: src/game/control_keys.cpp.s

.PHONY : src/game/control_keys.s

# target to generate assembly for a file
src/game/control_keys.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/control_keys.cpp.s
.PHONY : src/game/control_keys.cpp.s

src/game/controller.o: src/game/controller.cpp.o

.PHONY : src/game/controller.o

# target to build an object file
src/game/controller.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/controller.cpp.o
.PHONY : src/game/controller.cpp.o

src/game/controller.i: src/game/controller.cpp.i

.PHONY : src/game/controller.i

# target to preprocess a source file
src/game/controller.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/controller.cpp.i
.PHONY : src/game/controller.cpp.i

src/game/controller.s: src/game/controller.cpp.s

.PHONY : src/game/controller.s

# target to generate assembly for a file
src/game/controller.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/controller.cpp.s
.PHONY : src/game/controller.cpp.s

src/game/game.o: src/game/game.cpp.o

.PHONY : src/game/game.o

# target to build an object file
src/game/game.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game.cpp.o
.PHONY : src/game/game.cpp.o

src/game/game.i: src/game/game.cpp.i

.PHONY : src/game/game.i

# target to preprocess a source file
src/game/game.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game.cpp.i
.PHONY : src/game/game.cpp.i

src/game/game.s: src/game/game.cpp.s

.PHONY : src/game/game.s

# target to generate assembly for a file
src/game/game.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game.cpp.s
.PHONY : src/game/game.cpp.s

src/game/game_config.o: src/game/game_config.cpp.o

.PHONY : src/game/game_config.o

# target to build an object file
src/game/game_config.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game_config.cpp.o
.PHONY : src/game/game_config.cpp.o

src/game/game_config.i: src/game/game_config.cpp.i

.PHONY : src/game/game_config.i

# target to preprocess a source file
src/game/game_config.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game_config.cpp.i
.PHONY : src/game/game_config.cpp.i

src/game/game_config.s: src/game/game_config.cpp.s

.PHONY : src/game/game_config.s

# target to generate assembly for a file
src/game/game_config.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game_config.cpp.s
.PHONY : src/game/game_config.cpp.s

src/game/game_object.o: src/game/game_object.cpp.o

.PHONY : src/game/game_object.o

# target to build an object file
src/game/game_object.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game_object.cpp.o
.PHONY : src/game/game_object.cpp.o

src/game/game_object.i: src/game/game_object.cpp.i

.PHONY : src/game/game_object.i

# target to preprocess a source file
src/game/game_object.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game_object.cpp.i
.PHONY : src/game/game_object.cpp.i

src/game/game_object.s: src/game/game_object.cpp.s

.PHONY : src/game/game_object.s

# target to generate assembly for a file
src/game/game_object.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/game_object.cpp.s
.PHONY : src/game/game_object.cpp.s

src/game/main.o: src/game/main.cpp.o

.PHONY : src/game/main.o

# target to build an object file
src/game/main.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/main.cpp.o
.PHONY : src/game/main.cpp.o

src/game/main.i: src/game/main.cpp.i

.PHONY : src/game/main.i

# target to preprocess a source file
src/game/main.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/main.cpp.i
.PHONY : src/game/main.cpp.i

src/game/main.s: src/game/main.cpp.s

.PHONY : src/game/main.s

# target to generate assembly for a file
src/game/main.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/main.cpp.s
.PHONY : src/game/main.cpp.s

src/game/map.o: src/game/map.cpp.o

.PHONY : src/game/map.o

# target to build an object file
src/game/map.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/map.cpp.o
.PHONY : src/game/map.cpp.o

src/game/map.i: src/game/map.cpp.i

.PHONY : src/game/map.i

# target to preprocess a source file
src/game/map.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/map.cpp.i
.PHONY : src/game/map.cpp.i

src/game/map.s: src/game/map.cpp.s

.PHONY : src/game/map.s

# target to generate assembly for a file
src/game/map.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/map.cpp.s
.PHONY : src/game/map.cpp.s

src/game/player.o: src/game/player.cpp.o

.PHONY : src/game/player.o

# target to build an object file
src/game/player.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/player.cpp.o
.PHONY : src/game/player.cpp.o

src/game/player.i: src/game/player.cpp.i

.PHONY : src/game/player.i

# target to preprocess a source file
src/game/player.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/player.cpp.i
.PHONY : src/game/player.cpp.i

src/game/player.s: src/game/player.cpp.s

.PHONY : src/game/player.s

# target to generate assembly for a file
src/game/player.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/player.cpp.s
.PHONY : src/game/player.cpp.s

src/game/tile.o: src/game/tile.cpp.o

.PHONY : src/game/tile.o

# target to build an object file
src/game/tile.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/tile.cpp.o
.PHONY : src/game/tile.cpp.o

src/game/tile.i: src/game/tile.cpp.i

.PHONY : src/game/tile.i

# target to preprocess a source file
src/game/tile.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/tile.cpp.i
.PHONY : src/game/tile.cpp.i

src/game/tile.s: src/game/tile.cpp.s

.PHONY : src/game/tile.s

# target to generate assembly for a file
src/game/tile.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/tile.cpp.s
.PHONY : src/game/tile.cpp.s

src/game/tile_view.o: src/game/tile_view.cpp.o

.PHONY : src/game/tile_view.o

# target to build an object file
src/game/tile_view.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/tile_view.cpp.o
.PHONY : src/game/tile_view.cpp.o

src/game/tile_view.i: src/game/tile_view.cpp.i

.PHONY : src/game/tile_view.i

# target to preprocess a source file
src/game/tile_view.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/tile_view.cpp.i
.PHONY : src/game/tile_view.cpp.i

src/game/tile_view.s: src/game/tile_view.cpp.s

.PHONY : src/game/tile_view.s

# target to generate assembly for a file
src/game/tile_view.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/tile_view.cpp.s
.PHONY : src/game/tile_view.cpp.s

src/game/unit.o: src/game/unit.cpp.o

.PHONY : src/game/unit.o

# target to build an object file
src/game/unit.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/unit.cpp.o
.PHONY : src/game/unit.cpp.o

src/game/unit.i: src/game/unit.cpp.i

.PHONY : src/game/unit.i

# target to preprocess a source file
src/game/unit.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/unit.cpp.i
.PHONY : src/game/unit.cpp.i

src/game/unit.s: src/game/unit.cpp.s

.PHONY : src/game/unit.s

# target to generate assembly for a file
src/game/unit.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/unit.cpp.s
.PHONY : src/game/unit.cpp.s

src/game/unit_view.o: src/game/unit_view.cpp.o

.PHONY : src/game/unit_view.o

# target to build an object file
src/game/unit_view.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/unit_view.cpp.o
.PHONY : src/game/unit_view.cpp.o

src/game/unit_view.i: src/game/unit_view.cpp.i

.PHONY : src/game/unit_view.i

# target to preprocess a source file
src/game/unit_view.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/unit_view.cpp.i
.PHONY : src/game/unit_view.cpp.i

src/game/unit_view.s: src/game/unit_view.cpp.s

.PHONY : src/game/unit_view.s

# target to generate assembly for a file
src/game/unit_view.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/game/unit_view.cpp.s
.PHONY : src/game/unit_view.cpp.s

src/network/server.o: src/network/server.cpp.o

.PHONY : src/network/server.o

# target to build an object file
src/network/server.cpp.o:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/src/network/server.cpp.o
.PHONY : src/network/server.cpp.o

src/network/server.i: src/network/server.cpp.i

.PHONY : src/network/server.i

# target to preprocess a source file
src/network/server.cpp.i:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/src/network/server.cpp.i
.PHONY : src/network/server.cpp.i

src/network/server.s: src/network/server.cpp.s

.PHONY : src/network/server.s

# target to generate assembly for a file
src/network/server.cpp.s:
	$(MAKE) -f CMakeFiles/ser.dir/build.make CMakeFiles/ser.dir/src/network/server.cpp.s
.PHONY : src/network/server.cpp.s

src/painter/painter.o: src/painter/painter.cpp.o

.PHONY : src/painter/painter.o

# target to build an object file
src/painter/painter.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/painter/painter.cpp.o
.PHONY : src/painter/painter.cpp.o

src/painter/painter.i: src/painter/painter.cpp.i

.PHONY : src/painter/painter.i

# target to preprocess a source file
src/painter/painter.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/painter/painter.cpp.i
.PHONY : src/painter/painter.cpp.i

src/painter/painter.s: src/painter/painter.cpp.s

.PHONY : src/painter/painter.s

# target to generate assembly for a file
src/painter/painter.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/painter/painter.cpp.s
.PHONY : src/painter/painter.cpp.s

src/painter/shapes.o: src/painter/shapes.cpp.o

.PHONY : src/painter/shapes.o

# target to build an object file
src/painter/shapes.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/painter/shapes.cpp.o
.PHONY : src/painter/shapes.cpp.o

src/painter/shapes.i: src/painter/shapes.cpp.i

.PHONY : src/painter/shapes.i

# target to preprocess a source file
src/painter/shapes.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/painter/shapes.cpp.i
.PHONY : src/painter/shapes.cpp.i

src/painter/shapes.s: src/painter/shapes.cpp.s

.PHONY : src/painter/shapes.s

# target to generate assembly for a file
src/painter/shapes.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/painter/shapes.cpp.s
.PHONY : src/painter/shapes.cpp.s

src/utils/utils.o: src/utils/utils.cpp.o

.PHONY : src/utils/utils.o

# target to build an object file
src/utils/utils.cpp.o:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/utils/utils.cpp.o
.PHONY : src/utils/utils.cpp.o

src/utils/utils.i: src/utils/utils.cpp.i

.PHONY : src/utils/utils.i

# target to preprocess a source file
src/utils/utils.cpp.i:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/utils/utils.cpp.i
.PHONY : src/utils/utils.cpp.i

src/utils/utils.s: src/utils/utils.cpp.s

.PHONY : src/utils/utils.s

# target to generate assembly for a file
src/utils/utils.cpp.s:
	$(MAKE) -f CMakeFiles/syla.dir/build.make CMakeFiles/syla.dir/src/utils/utils.cpp.s
.PHONY : src/utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ser"
	@echo "... syla"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/game/control_keys.o"
	@echo "... src/game/control_keys.i"
	@echo "... src/game/control_keys.s"
	@echo "... src/game/controller.o"
	@echo "... src/game/controller.i"
	@echo "... src/game/controller.s"
	@echo "... src/game/game.o"
	@echo "... src/game/game.i"
	@echo "... src/game/game.s"
	@echo "... src/game/game_config.o"
	@echo "... src/game/game_config.i"
	@echo "... src/game/game_config.s"
	@echo "... src/game/game_object.o"
	@echo "... src/game/game_object.i"
	@echo "... src/game/game_object.s"
	@echo "... src/game/main.o"
	@echo "... src/game/main.i"
	@echo "... src/game/main.s"
	@echo "... src/game/map.o"
	@echo "... src/game/map.i"
	@echo "... src/game/map.s"
	@echo "... src/game/player.o"
	@echo "... src/game/player.i"
	@echo "... src/game/player.s"
	@echo "... src/game/tile.o"
	@echo "... src/game/tile.i"
	@echo "... src/game/tile.s"
	@echo "... src/game/tile_view.o"
	@echo "... src/game/tile_view.i"
	@echo "... src/game/tile_view.s"
	@echo "... src/game/unit.o"
	@echo "... src/game/unit.i"
	@echo "... src/game/unit.s"
	@echo "... src/game/unit_view.o"
	@echo "... src/game/unit_view.i"
	@echo "... src/game/unit_view.s"
	@echo "... src/network/server.o"
	@echo "... src/network/server.i"
	@echo "... src/network/server.s"
	@echo "... src/painter/painter.o"
	@echo "... src/painter/painter.i"
	@echo "... src/painter/painter.s"
	@echo "... src/painter/shapes.o"
	@echo "... src/painter/shapes.i"
	@echo "... src/painter/shapes.s"
	@echo "... src/utils/utils.o"
	@echo "... src/utils/utils.i"
	@echo "... src/utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

